### ISSUE TITLE
Makefile adjustment

### ISSUE THREAD

**Issue by Spacewalker2** [ltworf/weborf#21]
Please change makefile to:

```
install -D -m644 daemon/weborf.service $(DESTDIR)/usr/lib/systemd/system/weborf.service
install -D -m644 daemon/weborf@.service $(DESTDIR)/usr/lib/systemd/system/weborf@.service
install -D daemon/weborf-generator $(DESTDIR)/usr/lib/systemd/system-generators/weborf-generator
```

These files using /usr/lib:
```
weborf_cgi_wrapper
weborf_py_wrapper
```
These files using /lib:
```
weborf.service
weborf@.service
weborf-generator
```

The different paths causing trouble in creating a packet. Thanks.

**Comment by ltworf** [comment]
I guess I can change the service files path… anyway debhelper is moving them to /lib.

I got rid of the wrapper things in master, so that path won't be there any longer.

**Comment by ltworf** [comment]
I tried moving the service files as you asked and lintian gives an error

```
E: weborf-daemon: systemd-service-file-outside-lib usr/lib/systemd/system/weborf.service
N: 
N:    The package ships a systemd service file outside /lib/systemd/system/
N:    
N:    Systemd in Debian searches for unit files in /lib/systemd/system/ and
N:    /etc/systemd/system. Notably, it does <not> look in
N:    /usr/lib/systemd/system/ for service files.
N:    
N:    System administrators should have the possibility to overwrite a service
N:    file (or parts of it, in newer systemd versions) by placing a file in
N:    /etc/systemd/system, so the canonical location used for service files is
N:    /lib/systemd/system/.
N:    
N:    Severity: serious, Certainty: certain
N:    
N:    Check: systemd, Type: binary
N: 
E: weborf-daemon: systemd-service-file-outside-lib usr/lib/systemd/system/weborf@.service
```

So they are installed where they are supposed to be installed.

Closing this.

**Comment by Spacewalker2** [comment]
I tried to build a package for [AUR](https://aur.archlinux.org). Maybe it is possible to change the location of the wrapper files to /lib. I guess this would do the trick too.

**Comment by Spacewalker2** [comment]
It seems that arch linux uses a symlink from /lib to /usr/lib effects the package manager and this is deliberately. So I try to use a bind mount in the package then it should work as it is.

**Comment by ltworf** [comment]
Can't you patch the makefile?

The wrappers will be gone anyway in the next release.

**Comment by Spacewalker2** [comment]
I added now a simple workaround for the service files with mkdir, mv and rm to the PKGBUILD file and it works. It seems it is a symlink issue so it has to be done in the future too.

**Comment by ltworf** [comment]
Try to see how it works for you if you try to make a package from master, if you want to see how it will be.

You need to run make dist to generate a release tar file.

**Comment by Spacewalker2** [comment]
Thanks. I keep this in mind. I plan to create to 2 versions of the package one that uses the release tar file and another from master. I made some adjustments too. Now it doesn't matter how many files are in /lib everyone will be moved to /usr/lib. If this works well and i'm able to adopt the existing weborf package from AUR then I plan to create 2 versions for the gui too.

**Comment by Spacewalker2** [comment]
So it seems that I have a working package for [weborf](https://aur.archlinux.org/packages/weborf) and [qweborf](https://aur.archlinux.org/packages/qweborf) which is using the tar file from github. Here I have to wait for the disown of the current maintainer but locally it worked.

I have a working package already on [weborf-git](https://aur.archlinux.org/packages/weborf-git). I tried the same with [qweborf-git](https://aur.archlinux.org/packages/qweborf-git) and the install process worked but I get this error if I try to start qweborf.
```
Traceback (most recent call last):
  File "/bin/qweborf", line 21, in <module>
    import qweborf.qweborf
ModuleNotFoundError: No module named 'qweborf.qweborf'
```
I'm not sure this is a package thing and I have picked the wrong files or it is because I worked here with a git clone. Do you have any suggestions?

**Comment by Spacewalker2** [comment]
I found this https://wiki.debian.org/UsrMerge which links to http://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge. Maybe when buster is stable this will solve the issue.

**Comment by ltworf** [comment]
No it's merged only if the user wants, not by default and not on all systems anyway.
