### ISSUE TITLE
Odd Qweborf Error:  `/home/phil/usr/bin/python3: not found`

### ISSUE THREAD

**Issue by anoduck** [ltworf/weborf#3]
Attempted to install Qweborf today, totally stocked about it. Upon running `pyuic5 qweborf/main.ui > qweborf/main.py` , received the oddest error message. `/usr/local/bin/pyuic5: 2: exec: /home/phil/usr/bin/python3: not found` 
I don't know anyone named phil who runs linux. Wondering how I can reset that python path? I have attempted to use the `env` command, to no avail. 

Cheers

**Comment by ltworf** [comment]
there is no `phil` in this repository, can you paste the output of your `env` command?

**Comment by anoduck** [comment]
Yes, Sir... You are correct, and I apologize. I realized the 'phil' error was coming from my installation of pyqt5. I am working on resolving it and reinstalling it. But just FYI, my env is:
```
`ARCHFLAGS=-arch x86_64                                                                                                                                                        [0/462]
SSH_KEY_PATH=~/.ssh/dsa_id
ALTERNATE_EDITOR=vim
EDITOR=gvim
VISUAL=gvim
TEXINPUTS=.:/home/anonymousdude/.emacs.d/elpa/auctex-11.89.4/latex:
PROMPT_EOL_MARK=
GPG_TTY=/dev/pts/3
PYTHONPATH=/usr/local/lib/python2.7
MAIL=/var/spool/mail/anonymousdude
CONFIG=/home/anonymousdude/.tommy.cfg
rvm_prefix=/home/anonymousdude
rvm_path=/home/anonymousdude/.rvm
rvm_bin_path=/home/anonymousdude/.rvm/bin
_system_type=Linux
_system_name=Ubuntu
_system_version=16.04
_system_arch=x86_64
rvm_version=1.26.11 (latest)
GEM_HOME=/home/anonymousdude/.rvm/gems/ruby-2.2.4
GEM_PATH=/home/anonymousdude/.rvm/gems/ruby-2.2.4:/home/anonymousdude/.rvm/gems/ruby-2.2.4@global
MY_RUBY_HOME=/home/anonymousdude/.rvm/rubies/ruby-2.2.4
IRBRC=/home/anonymousdude/.rvm/rubies/ruby-2.2.4/.irbrc
RUBY_VERSION=ruby-2.2.4
```
I am not sure if it is kosher as of yet, but I am considering changing my $PYTHONPATH to version 3.5 and see if that removes the error...

Cheers, 
Thanks for sweet software...

**Comment by ltworf** [comment]
But why don't you just use packages from your distribution instead of messing up things?
