### ISSUE TITLE
Help in setting up authentication

### ISSUE THREAD

**Issue by pepa65** [ltworf/weborf#4]
I used qweborf before with authentication, but now I need to set up weborf on a headless server, with authentication. Could you give some pointers how I can set up credentials? On Ubuntu there's a package weborf-daemon, but I couldn't figure out how to set up the authentication part.

**Comment by ltworf** [comment]
weborf doesn't have a configuration for the authentication. It accepts a unix socket and sends everything to an external program that needs to decide whether to deny or allow the request.

Check the file `/usr/share/doc/weborf/examples/auth.py`, it contains a minimal example of such program.

It creates a unix socket which you then have to pass to weborf with the `--auth` option.

If you don't want to have an external process running, you can recompile weborf hardcoding the authentication in the file `embedded_auth.h`.

**Comment by pepa65** [comment]
In `embedded_auth.h` I uncommented `#define EMBEDDED_AUTH` and recompiled, but this didn't turn on any authentication. Is there something more that needs to be done for this?

**Comment by ltworf** [comment]
Run it with `./weborf -a asdasd` (it doesn't matter the value you pass, just that it will enable the authentication).

**Comment by pepa65** [comment]
It doesn't give an error like when embedded is not enabled, but there is no asking for credentials, it just gives access. Is there anything else I can change to make this work?

**Comment by ltworf** [comment]
Well the default code there isn't blocking access to everything, try putting a `printf` to make sure it is run, and then make your own thing.

**Comment by ltworf** [comment]
When embedded is enabled, if you are running weborf with a `-a something` parameter on the command line, the code in `embedded_auth.h` should be running, and it doesn't ask for password for every request, only for some, so make sure to change it to what you need to do.

**Comment by pepa65** [comment]
OK, got it! I moved the line `return emb_check_password(username,password);` to the top of `c_auth` to always require authentication.
(I also added commandline options for username and password, so I am set! Thanks for your help.)
