### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by JamesOlvertone** [ltworf/weborf#51]
_man page
-a, --auth
 Must be followed by a unix socket listened by a program who will handle authentication. See the website for more details.
On the website are no details, there is nothing documented anywhere._

It cannot be used without auth. With this Qt-Frontend it works but only if you enable "Webdav" the has nothing to do with auth but its listed under "auth". In the generated command line a "-a /temp/weborf-socke..." appears., that gives you a hint you have to use it anyway, but how without this qt frontend, I dont want this frontend.

Document this software better, it unusable without a description.

**Comment by ltworf** [comment]
This: https://github.com/ltworf/weborf/blob/master/examples/auth.py
