### ISSUE TITLE
Request: Save settings in GUI

### ISSUE THREAD

**Issue by rojmiller** [ltworf/weborf#59]
I am new to Linux, but have the GUI version up and running successfully. Works well.

Is there any way to add a save  settings to the GUI, e.g., "Directory to Share". "Try to Share outside LAN", and lastly an automatic "Start Sharing" on startup?

**Comment by ltworf** [comment]
I think there could be a button like "save settings as default" maybe?

Any chance you'd want to implement this?

**Comment by rojmiller** [comment]
A "Save settings as default" button would be great, as well as a checkbox to "Start sharing on startup"
