### ISSUE TITLE
use setgid()

### ISSUE THREAD

**Issue by marsie** [ltworf/weborf#6]
Hi.
May you implement an option to set the group of the weborf process? I've patched weborf to call setgid() with a hardcoded gid before calling setuid(), but a commandline parameter would be nice.

**Comment by pepa65** [comment]
Thanks for requesting this, I have incorporated this in https://github.com/pepa65/weborf
Note, you have to make sure that the calling proces has CAP_SETGID capabilities.
I am sure LtWorf will respond in his own time.

**Comment by ltworf** [comment]
Yes yes thanks for the unwarranted sarcasm @pepa65. Of course I can't just copy your commits because of the swarm of unrelated changes that are in them.

Also, you didn't change the manpage, the help and the init script.

**Comment by pepa65** [comment]
I am sorry, that was not intended to be sarcasm. I think you're running a wonderful project. I myself know very little about this. I learn a lot by seeing what you do.

Thank you for pointing out the things I forgot, I will take care of that. For my personal use, I only use the binary, so I should check all the other places.

**Comment by pepa65** [comment]
By the way, I found the man page was missing a number of options.
