### ISSUE TITLE
libc6 2.33 dependency

### ISSUE THREAD

**Issue by rojmiller** [ltworf/weborf#65]
Your latest version (0.18.1) requires libc6 >= 2.33. For those of us running Ubuntu 20.04.4 LTS, 0.18.1 won't install, because for Ubuntu 20.04.4, libc6 2.31 is the latest version available.

**Comment by ltworf** [comment]
Download the tar file and recompile.

It's not a "requirement", it's only that it was built against that version of libc.

You can download the .orig file and the debian directory and rebuild on your machine.

I use debian testing so ubuntu 20.04 is 2 years behind what I have.

**Comment by ltworf** [comment]
```
tar -xf weborf_0.18.orig.tar.gz; tar -xf weborf_0.18-1.debian.tar.xz; mv debian weborf-0.18; cd weborf-0.18; dpkg-buildpackage 
```

That's it.

It will fail if you don't have the required libraries installed to build it.

**Comment by rojmiller** [comment]
Unfortunately the build itself seems to have a dependency on a later version of Linux as well:
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 13) debhelper (>= 13)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

I then ran it with the -d flag and it ran for a while and ended with:
dpkg-buildpackage: info: full upload (original source is included)                                                   
 signfile weborf_0.18-1.dsc
gpg: skipped "Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it>": No secret key                                         
gpg: dpkg-sign.sN3er3Qj/weborf_0.18-1.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file

So it can't be built on 20.04?

**Comment by ltworf** [comment]
@rojmiller quite sure it can, just run configure  and make and replace the binary in /usr/bin :D

Or use the new tar.gz with the old debian directory (adapting the debian/changelog file or it doesn't build).

But at the end why do you use a stable distribution and want new stuff? If you want new stuff stable distributions aren't really well suited.

**Comment by rojmiller** [comment]
I realize that you are probably not interested in supporting this for the LTS version of Ubuntu, but fyi here's what happens when I follow your instructions:

dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 13) debhelper (>= 13)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

So even the builder wants a newer version of Ubuntu

Then using the -d flag to override:
It seems to work, building the deb files but ends with this:

gpg: skipped "Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it>": No secret key                                         
gpg: dpkg-sign.0oUgdqTB/weborf_0.18-1.dsc: clear-sign failed: No secret key
dpkg-buildpackage: error: failed to sign .dsc file

When I install the two files (without any errors reported) it says that I have 0.18.1 version of both weborf and qweborf, but the interface looks the same - there is no Save button or any new features that I can see. As well, the program no longer works! 
I am "trying to share outside LAN", but get the message "Could not create NAT route" (this works for me on 0.16.1)

**Comment by rojmiller** [comment]
@ltworf _But at the end why do you use a stable distribution and want new stuff? If you want new stuff stable distributions aren't really well suited_.

Because I am very new to Linux (from Windows) and don't know what is possible or not? Linux takes a lot of getting used to....

**Comment by ltworf** [comment]
My advice is to stick with using whatever is on your distribution.

If you need some specific feature that is in the newer versions, the easier way is to just upgrade the entire ubuntu to one of the non-stable versions that they put out every 6 months.
