### ISSUE TITLE
strange CLI startup issue

### ISSUE THREAD

**Issue by mdziczkowski** [ltworf/weborf#69]
### System information

**OS**: Debian 11
**GUI**: X11 + openbox + LXQT

### Problem description

I'm attempting to run weborf from a script using following syntax 

```
weborf -d -m -p 80 -b [here goes the path to my WWW root dir]
```

and I recieve an error that the typed as the "-b" parameter path need to be a directory (with is and it has propper permissions)

**Comment by ltworf** [comment]
Please give me the full command you passed, the full output you got, and also run `stat` against the directory you want to target.

Also to use port 80 you need to be root or have the appropriate capability.

**Comment by mdziczkowski** [comment]
> Please give me the full command you passed, the full output you got, and also run `stat` against the directory you want to target.

Please read my ticket again wirh understanding because I had already posted the whole comand and stat return correct values

**Comment by ltworf** [comment]
No you didn't.

But thanks for insulting me while I try to help you. You can figure it out yourself.
