### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by fometeo** [ltworf/weborf#80]
I would like to know where are the weborf logs

**Comment by ltworf** [comment]
the logs are with the rest of the system log. Most likely in journald.

https://www.freedesktop.org/software/systemd/man/journalctl.html

**Comment by fometeo** [comment]
alright; that means getting logs by: **journalctl -t weborf**

I was wondering if it has it's own file, besides entries at /var/log/syslog and a few at /var/log/boot.log and /var/log/dmesg

Thank you

**Comment by ltworf** [comment]
That depends entirely on how your system is configured. weborf just uses the syslog() call, then your logging daemon (rsyslog or journald) can be configured in various ways, to store in different files, forward remotely… the most common default setup is to have both journald and rsyslog, but again, this has nothing to do with weborf.
